services:
  queue-telegram:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: queue-telegram-app
    restart: always
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    depends_on:
      - postgresql
    networks:
      - telegram-network

  webserver:
    image: nginx:1.27-alpine
    container_name: queue-telegram-webserver
    depends_on:
      - queue-telegram
    restart: always
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - telegram-network

  postgresql:
    image: postgres:17-alpine
    container_name: queue-telegram-postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - telegram-network

volumes:
  dbdata:

networks:
  telegram-network:
    driver: bridge